name: Deploy App
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options: 
        - Staging 
        - Production

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
