name: Deploy App
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment
        required: true
        options: 
        - Staging 
        - Production
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
