name: Validate pod
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-11
    steps:
    - name: Cancel previous jobs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.10.2
    - name: Add AZ repo Spec
      run: pod repo add az-test-spec https://zalazara:${{ secrets.GTOKEN }}@github.com/zalazara/az-test-spec.git
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        test: false
        additional_lint_params: --allow-warnings --sources=https://cdn.cocoapods.org/,https://github.com/zalazara/az-test-spec.git --verbose