name: Publish pod
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.4.1
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.9.0
      - name: Publish pod
        uses: maxep/pod-repo-push-action@0.1.2
        with:
          repo-url: https://zalazara:${{ secrets.GTOKEN }}@github.com/zalazara/az-test-spec.git
          args: --allow-warnings --sources=https://cdn.cocoapods.org/,https://github.com/zalazara/az-test-spec.git